
name: Notify (IFTTT integration)

on:
  workflow_call:
    inputs:
      type:
        description: 'Notification type (Success, Error, Pending)'
        required: true
        default: 'error'
        type: string
      repoName:
        description: 'Repository name'
        required: true
        default: ''
        type: string
      branch:
        description: 'Branch name'
        required: false
        default: ''
        type: string
      details:
        description: 'Notification message'
        required: false
        default: ''
        type: string
      repoLink:
        description: 'Repository link'
        required: false
        default: ''
        type: string
    secrets:
      IFTTT_KEY:
        description: 'IFTTT key'
        required: true

env: 
  IFTTT_EVENT: 'ga_notify'
  IFTTT_API: 'https://maker.ifttt.com/trigger/$IFTTT_EVENT/json/with/key/${{ secrets.IFTTT_KEY }}'
  HEADER: '{"Content-Type": "application/json"}'

jobs:
  test-caller:
    runs-on: ubuntu-latest
    steps:
    - name: Print params
      run: |
        echo "type: ${{ inputs.type }}"
        echo "repoName: ${{ inputs.repoName }}"
        echo "branch: ${{ inputs.branch }}"
        echo "details: ${{ inputs.details }}"
        echo "repoLink: ${{ inputs.repoLink }}"
  # execute-ifttt-webhook:
  #   runs-on: ubuntu-latest 
  #   steps:
  #   - name: Notify execution
  #     uses: fjogeleit/http-request-action@v1
  #     with:
  #       url: $IFTTT_API
  #       method: 'POST'
  #       customHeaders: $HEADER
  #       data: '{"repoName": "${{ inputs.repoName }} - ${{ inputs.branch }}","status": "${{ inputs.type }}","details": "${{ inputs.details }}","repoLink": "${{ inputs.repoLink }}"}'
