
name: Manually Triggered Workflow

on: workflow_dispatch

jobs:
  announce-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run script
        run: |
          echo "Running workflow caller script"
      - id: foo
        uses: fragnarok/notify-action@v1.0.3-beta
        with:
           details: "This is a test, nice!"
           type: "success"
           branch: "main"
           repoName: "TestingRepo"
           repoLink: "https://github.com/FragnaroK/Custom-GitHub-Action-Scripts" 
           IFTTT_KEY: "${{ secrets.IFTTT_KEY }}"